apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ml
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
     - ReadWriteOnce
  claimRef:
    name: ml-pvc
    namespace: ahmad
  hostPath:
     path: /home/ahmad

