apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-score
spec:
  selector:
    matchLabels:
      app: score-script
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: score-script
    spec:
      containers:
      - name: script
        image: aneequekhalid/scoring:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
          - mountPath: /models
            name: test-volume
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
       - name: test-volume
         persistentVolumeClaim:
           claimName: ml-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 8080
    targetPort: 5000
    name: http
  selector:
    app: score-script
