apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  # echo -n "cookie-value" | base64
  azurestorageaccountname: YWhtYWRwb2M=
  azurestorageaccountkey: Wmx2cVNlQUEvSEx6Mnd0cFhOY2hvbGNiNzRLWXp2Q0JJTGVXblN1OUFFRUwyYnJZSkZ5V3N4U0tRSnRIZ2hyRHZZbjVPQUc4bGFON29hWnJ2NkZhSVE9PQ==
