apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: mangment
