apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-29T10:42:35Z"
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: definition
    app.kubernetes.io/part-of: rabbitmq
  name: definition-rabbitmq-client
  namespace: rabbit
  ownerReferences:
  - apiVersion: rabbitmq.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: RabbitmqCluster
    name: definition
    uid: fb4c7278-5a2e-450a-87f0-bde78c1a1ca0
  resourceVersion: "827274"
  selfLink: /api/v1/namespaces/rabbit/services/definition-rabbitmq-client
  uid: 2a80f694-cb08-42fc-b814-51c8107af335
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: management
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app.kubernetes.io/name: definition
  sessionAffinity: None
  type: LoadBalancer
