apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"




#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: jenkins
#  labels:
#    usage: jenkins-storage
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  azureFile:
#    secretName: azure-secret
#    shareName: akztest
#    readOnly: false
#  claimRef:
#    name: jenkins-claim
#    kind: PersistenVolumeClaim
#    namespace: jenkins
#  persistentVolumeReclaimPolicy: Retain

