apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    usage: jenkins-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    secretNamespace: jenkins
    shareName: k8stest
    readOnly: false
  claimRef:
    name: jenkins-claim
    kind: PersistenVolumeClaim
    namespace: jenkins
  persistentVolumeReclaimPolicy: Retain

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins
#   #annotations: 
#    #pv.beta.kubernetes.io/gid: "1000"
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#   - ReadWriteOnce
#   azureFile:
#     secretName: storage-connection
#     secretNamespace: jenkins
#     shareName: aksshare
#     readOnly: false
#   claimRef:
#     name: jenkins-pvc
#     kind: PersistenVolumeClaim
#     namespace: jenkins
#   persistentVolumeReclaimPolicy: Retain
